### ISSUE TITLE
[NEAT-219] issue by non-member

### ISSUE THREAD

**Issue by spareted** [neat-run/linear-to-github#14]
cannot add labels nor assignees

**Comment by tedspare** [comment]
This is a short comment on a GitHub issue

> [🔄](https://synclinear.com)

**Comment by tedspare** [comment]
<sub>test</sub>

> 🔄

> From Ted Spare on Linear

**Comment by tedspare** [comment]
comment in GH

**Comment by tedspare** [comment]
comment in Lin

> From Ted Spare on Linear

**Comment by tedspare** [comment]
test hidden text

**Comment by tedspare** [comment]
test on Lin

> From Ted Spare on Linear

**Comment by tedspare** [comment]
didn't work on Linear; test another method

[This is a comment that will be hidden.]: #

**Comment by tedspare** [comment]
hidden text in Linear

[This is a comment that will be hidden.]: #

**Comment by tedspare** [comment]
hidden text from Lin

\[This is a comment that will be hidden.\]: #

> From Ted Spare on Linear

**Comment by tedspare** [comment]
```
[This is a comment that will be hidden.]: #
```

anotha one

\[This is a comment that will be hidden.\]: #

> From Ted Spare on Linear

**Comment by tedspare** [comment]
requires blank lines before and after

1

```
[This is a comment that will be hidden.]: #
```

\[This is a comment that will be hidden.\]: #

> From Ted Spare on Linear

**Comment by tedspare** [comment]
requires blank lines before and after

1

```
[This is a comment that will be hidden.]: #
```

2

\[This is a comment that will be hidden.\]: #

3 body could go here

> From Ted Spare on Linear

**Comment by tedspare** [comment]
requires blank lines before and after

2

\\n\[This is a comment that will be hidden.\]: #\\n

3 

\[This is a comment that will be hidden.\]: #

4

> From Ted Spare on Linear

**Comment by tedspare** [comment]
\[comment\]: 

> From Ted Spare on Linear

**Comment by tedspare** [comment]
Here's a paragraph that will be visible.

[This is a comment that will be hidden.]: # 

And here's another paragraph that's visible.

**Comment by tedspare** [comment]
Here's a paragraph that will be visible.

And here's another paragraph that's visible.

> From Ted Spare on Linear

**Comment by tedspare** [comment]
Here's a paragraph that will be visible.

\[This is a comment that will be hidden.\]: #    

And here's another paragraph that's visible.

> From Ted Spare on Linear

**Comment by tedspare** [comment]
Here's a paragraph that will be visible.

[on Linear on GitHub]: #

And here's another paragraph that's visible.

**Comment by tedspare** [comment]
here's a normal comment

**Comment by tedspare** [comment]
here's a normal comment

> From Ted Spare on Linear

**Comment by tedspare** [comment]
comment should not double back

**Comment by tedspare** [comment]
comment should not double back

[From Ted Spare on Linear]: #

**Comment by tedspare** [comment]
hidden text is handled by linear

**Comment by tedspare** [comment]
hidden text is handled by linear

[From Ted Spare on Linear]: #

**Comment by tedspare** [comment]
html comment on GH side

**Comment by tedspare** [comment]
md comment on Lin, html comment on GH

**Comment by tedspare** [comment]
md comment on Lin, html comment on GH

**Comment by tedspare** [comment]
one more

**Comment by tedspare** [comment]
one more

**Comment by tedspare** [comment]
markdown comment

\[//\]: # (This is a comment.)

**Comment by tedspare** [comment]
another 

\[//\]: # (This is a comment.)

**Comment by tedspare** [comment]
html comment?

**Comment by tedspare** [comment]
empty URL?

\[proper url\](https://synclinear.com)

\[ \](https://example.com)

\[\](https://example.com)

**Comment by tedspare** [comment]
more attempts

```
```

(comment?)

\[comment in square brackets?\]: #abc

**Comment by tedspare** [comment]
hidden comment here

\[comment in here\]: #

**Comment by tedspare** [comment]
anotha one

\[comment here\]: #

.

**Comment by tedspare** [comment]
duplicates

**Comment by tedspare** [comment]
duplicates

**Comment by tedspare** [comment]
comment here

**Comment by tedspare** [comment]
again

**Comment by tedspare** [comment]
a third time

**Comment by tedspare** [comment]
a fourth time

**Comment by tedspare** [comment]
a fourth time

**Comment by tedspare** [comment]
try 5

**Comment by tedspare** [comment]
try 5

.

**Comment by tedspare** [comment]
subtle footer

**Comment by tedspare** [comment]
as attachment

**Comment by tedspare** [comment]
might work

**Comment by tedspare** [comment]
might work
[From Ted Spare on Linear]: #

**Comment by tedspare** [comment]
would this work?

[https://github.com/neat-run/linear-to-github/issues/14#issuecomment-1274965584](https://github.com/neat-run/linear-to-github/issues/14#issuecomment-1274965584)

**Comment by tedspare** [comment]
what about this?

**Comment by tedspare** [comment]
from Lin then

**Comment by tedspare** [comment]
a comment from GH

**Comment by tedspare** [comment]
uses id now

**Comment by tedspare** [comment]
must be a uid

**Comment by tedspare** [comment]
strictly uid

**Comment by tedspare** [comment]
strictly uid

**Comment by tedspare** [comment]
follows uid format

**Comment by tedspare** [comment]
substring

**Comment by tedspare** [comment]
all letters in substr

**Comment by tedspare** [comment]
hex-friendly suffix

**Comment by tedspare** [comment]
hex-friendly

**Comment by tedspare** [comment]
decafbad

**Comment by tedspare** [comment]
anotha

**Comment by tedspare** [comment]
what

**Comment by tedspare** [comment]
suffix

**Comment by tedspare** [comment]
formatting
