### ISSUE TITLE
[NEAT-198] Testing 2 - Cal <> Neat

### ISSUE THREAD

**Issue by Kamalmalikk** [neat-run/linear-to-github#8]
Creating another test issue for Linear <> GitHub sync
From Linear-GitHub Sync

**Comment by Kamalmalikk** [comment]
Testing Comment

**Comment by Kamalmalikk** [comment]
Testing tag @tedspare

**Comment by tedspare** [comment]
should be fixed now
<sub>Ted Spare on Linear</sub>

**Comment by tedspare** [comment]
comment should go back

**Comment by tedspare** [comment]
GH comment not synced?

**Comment by tedspare** [comment]
comment should sync back

**Comment by tedspare** [comment]
where does comment go

**Comment by tedspare** [comment]
comment syncs
